
before_script:
  - docker info

stages:
  - docker
  - test



run_tests:
  stage: test
  image: python:latest
  before_script:
    - pip install -r pybis/requirements.txt
  script:
    - python ./pybis/app/tests.py
  only:
    changes:
      - ./pybis/Dockerfile
      - ./pybis/requirements.txt
      - ./pybis/app/tests.py
