
before_script:
  - docker info

stages:
  - docker
  - test




services:
  - name: registry-1.docker.io/openbis/debian-openbis
    alias: openbis-local
    variables:
      #Here you can configure some openbis options for the AS
      SERVER_HOST_PORT: "localhost:8443"
      GROUP_ID: "1000"
      #Enable the basic plugins
      CORE_PLUGINS: "enabled-modules = dataset-uploader, dataset-file-search, xls-import, eln-lims, openbis-ng-ui, search-store, user-management-maintenance"



build-docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  tags:
    - dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build --pull -t $CI_REGISTRY_IMAGE ./pybis
    - docker push $CI_REGISTRY_IMAGE
  only:
    changes:
      - ./pybis/Dockerfile
      - ./pybis/requirements.txt
      - ./pybis/app/*





run-tests:
  stage: test
  image:
    name: $CI_REGISTRY_IMAGE
    entrypoint: [""]
  before_script:
    - /app/check_openbis.sh https://openbis-local:443
  script:
    - python /app/test.py
