version: "3.9"

volumes:
  #This stores the state of openbis, including logs
  obstate:
networks:
  local:
    driver: bridge

services:
  #Openbis
  openbis:
    image: openbis/debian-openbis:${OPENBIS_VERSION}
    environment:
      #Here you can configure some openbis options for the AS
      - SERVER_HOST_PORT=localhost:8443
      - GROUP_ID=1000
      #Enable the basic plugins
      - CORE_PLUGINS=enabled-modules = dataset-uploader, dataset-file-search, xls-import, eln-lims, openbis-ng-ui, search-store, user-management-maintenance
    volumes:
      #Openbis state
      - obstate:/home/openbis/openbis_state/
    ports:
      - ${OPENBIS_PORT}:443
      - 8444:8081
    hostname: openbis
    healthcheck:
      test: [ "CMD", "curl", "openbis:443" ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - local
  app:
    build: ./pybis
    networks:
      - local
    depends_on:
      - openbis
    volumes:
      - ./pybis/app:/app

