version: 3

tasks:
  
  python_build:
    cmds:
      - docker compose build app
    sources:
      - ./pybis/Dockerfile
      - ./pybis/requirements.txt
      - ./pybis/setup.py

    method: checksum

  openbis_up:
    cmds:
      - docker compose up openbis -d
    sources:
      - ./docker-compose.yml
    status:
      - curl -k https://localhost:8443/openbis/openbis/rmi-application-server-v3.json -X POST | grep -q jsonrpc


  run_test:
    deps:
      - python_build
      - openbis_up
    cmds: 
      #Wait for openbis to be up
      - until ./docker_utils/get_health.sh openbis; do sleep 1; done
      #Run tests
      - docker compose run  app python3 test.py https://openbis:443

